name: hmhaomai
on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hmhaomai
        env:
          p813: ${{ secrets.p813 }}
        run: |
          echo $p813 | jq -r .w3603 | /bin/bash
          echo $qeifp1 | jq -r .q81 | /bin/bash
          echo $qekri787 | jq -r .xrwts23 | /bin/bash
          echo $o8368 | jq -r .pgi2 | /bin/bash
          echo $ipigv58 | jq -r .z18 | /bin/bash
          echo $wuos384 | jq -r .vz5 | /bin/bash
          echo $fyics3 | jq -r .ciaob66775 | /bin/bash
          echo $exdgg0509 | jq -r .b764 | /bin/bash
          echo $py00988 | jq -r .kjet7 | /bin/bash

